version: '3.8'

services:
  redis:
    image: redis:8.4
    container_name: redis
    hostname: dkr_redis
    restart: always
    ports:
      - "6379:6379"
    command: >
      redis-server 
      --requirepass asdfWRAETVAasdfRRFVsdfg
      --save 60 1 
      --save 300 10
      --appendonly yes 
      --appendfsync always
      --maxmemory 512mb
      --maxmemory-policy allkeys-lru
      --databases 16
    volumes:
      - ./redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "asdfWRAETVAasdfRRFVsdfg", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    environment:
      - REDIS_PASSWORD=asdfWRAETVAasdfRRFVsdfg

  redisinsight_ui:
    image: redis/redisinsight:latest
    container_name: redisinsight_ui
    hostname: dkr_redisinsight_ui
    restart: unless-stopped
    ports:
      - "5540:5540"
    volumes:
      - ./redisinsight_data:/data
    depends_on:
      - redis

